keycloak:
  realm: REALM_SPRING_API
  auth-server-url: http://localhost:8080/auth/realms/${keycloak.realm}
  resource: CLIENT_SPRING
  credentials:
    secret: ZaV7QMccg1FfzPwLPULCnM2IIfkaFdTz
  user-login:
    grant-type: password


spring:
  application:
    :name: spring-keycloak
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${keycloak.resource}
            client-secret: ${keycloak.credentials.secret}
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: ${keycloak.auth-server-url}
            user-name-attribute: preferred_username


server:
  port: 8081


logging:
  level:
    org.springframework.security: DEBUG



